// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Secret struct {
	ID             uuid.UUID    `json:"id"`
	SecretText     string       `json:"secret_text"`
	PasswordHash   string       `json:"password_hash"`
	Salt           string       `json:"salt"`
	ExpiresAt      time.Time    `json:"expires_at"`
	CreatedAt      sql.NullTime `json:"created_at"`
	RemainingTries int32        `json:"remaining_tries"`
	LastViewedAt   sql.NullTime `json:"last_viewed_at"`
}
