services:
  postgres-ghost:
    image: postgres:17.0-alpine3.20
    networks:
      - ghost-network
    restart: unless-stopped
    hostname: postgres-ghost
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ghostsend", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ../.env

  frontend:
    image: cksidharthan/ghostsend-frontend:latest
    platform: linux/amd64
    ports:
      - "6666:3000"
    env_file:
      - ../.env
    networks:
      - ghost-network
    depends_on:
      - backend
      - postgres-ghost

  backend:
    image: cksidharthan/ghostsend-backend:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    networks:
      - ghost-network
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      postgres-ghost:
        condition: service_healthy

networks:
  ghost-network:
    driver: bridge
