services:
  postgres-secret:
    image: postgres:17.0-alpine3.20
    networks:
      - secret-network
    restart: unless-stopped
    hostname: postgres-secret
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "secret", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=secret

  app:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      args:
        - PORT=7780
    ports:
      - "7780:7780"
    networks:
      - secret-network
    environment:
      - PORT=7780
      - POSTGRES_HOST=postgres-secret
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=secret
      - POSTGRES_DRIVER=postgres
      - POSTGRES_SSL_MODE=disable
      - MIGRATION_PATH=/app/db/migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7780/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      postgres-secret:
        condition: service_healthy

networks:
  secret-network:
    driver: bridge
